language: python
sudo: require
python:
  - "3.4"
# command to install dependencies
install:
  - pip install twx.botapi
#  - sudo apt-get install pychecker

# command to run tests
script:
  - pwd
  - python -m compileall ./

#  pychecker doesn't work as expected for me. Until now i'm going with just syntax checking all the files.
#  - pychecker ./*.py

notifications:
  email: false